baseURL = 'https://codecaverna.tech/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'CODECAVERNA'

paginate = 5

[params]
    description = "Um blog de tecnologia direto ao ponto, simples sem ser simplório"
    dateFormat = "2 Jan, 2006"

[taxonomies]
    category = "categorias"
    author = "autores"



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 4

