baseURL = 'https://codecaverna.pages.dev/'
languageCode = 'pt-br'
title = 'CODECAVERNA'

paginate = 5

[params]
    dateFormat = "Jan 2, 2006"

[taxonomies]
    category = "categorias"
    author = "authors"