baseURL = 'https://codecaverna.tech/'
languageCode = 'pt-br'
defaultContentLanguage = 'pt-br'
title = 'CODECAVERNA'

paginate = 5

[params]
    description = "Um blog de tecnologia direto ao ponto, simples sem ser simplório"
    dateFormat = "2 Jan, 2006"

[taxonomies]
    category = "categorias"
    author = "autores"